Market Aid: All aboard 🚄
RubiconDeFi/rubi-bots pull request #6
Opened 2023-04-12 23:45 UTC by denverbaumgartner

adds the following functionality through an easy to use cli interface when running `npm run aid`

### npm run aid

this script provides the following functionality: 

    - [x] allow the user to connect to the market aid factory of the network 
        - [x] allow the user to view their market aids on the network 
        - [x] allow the user to connect to an existing market aid 
        - [x] allow the user to make a new market aid 
    - [x] allow the user to connect to a market aid and see
        - [x] check the market address 
        - [x] check the admin address
            - [x] check if the admin address is the same as the connected EOA
        - [x] check which strategists are approved 
        - [x] check the balance of the market aid contract 
    - [x] allow the user to connect to the market aid and do
        - [x] deposit to the aid 
        - [x] withdraw from the aid 
        - [x] pull all funds 
        - [x] approve a target venue 
        - [x] approve a strategist 
        - [x] remove a strategist 
    - [x] allow the user to batch calls to the erc20s on their network and
        - [x] the market aid balance 
        - [x] approve the market aid 

i think there is a lot more we can do here, but for now this should cover all needed functionality for the user when getting a market aid setup to run rubi-bots 🦖

2023-04-16 21:09 UTC, bghughes commented on configuration/README.md
> +JSON_RPC_URL_42161 = **insert your arbitrum one node http endpoint here**
This seems verbose/eyesore to me, can we explain that the last number is just chainID?

2023-04-16 21:22 UTC, denverbaumgartner commented on configuration/README.md
> +JSON_RPC_URL_42161 = **insert your arbitrum one node http endpoint here**
we could, my goal here was to have a file any end user could easily copy/paste and update with their own info without having to add in any new params. we could also have this be a separate page that we link to in this readme

2023-04-16 21:26 UTC, bghughes commented on configuration/README.md
> +JSON_RPC_URL_42161 = **insert your arbitrum one node http endpoint here**
Still, I feel the same line takes up half the README, they don't need to add support for all of them, just the ones they want to use. What about something like this:

`
<p style="border: 0px solid rgb(217, 217, 227); box-sizing: border-box; --tw-border-spacing-x:0; --tw-border-spacing-y:0; --tw-translate-x:0; --tw-translate-y:0; --tw-rotate:0; --tw-skew-x:0; --tw-skew-y:0; --tw-scale-x:1; --tw-scale-y:1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness:proximity; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; --tw-shadow:0 0 transparent; --tw-shadow-colored:0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; margin: 1.25em 0px; color: rgb(209, 213, 219); font-family: Söhne, ui-sans-serif, system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, &quot;Helvetica Neue&quot;, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(68, 70, 84); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Environment Variables
Set up the environment variables in your .env file with the appropriate values for each chainID you want to support. Refer to the Chain ID reference table below for the supported chains and their respective IDs.</p><p style="border: 0px solid rgb(217, 217, 227); box-sizing: border-box; --tw-border-spacing-x:0; --tw-border-spacing-y:0; --tw-translate-x:0; --tw-translate-y:0; --tw-rotate:0; --tw-skew-x:0; --tw-skew-y:0; --tw-scale-x:1; --tw-scale-y:1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness:proximity; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; --tw-shadow:0 0 transparent; --tw-shadow-colored:0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; margin: 1.25em 0px; color: rgb(209, 213, 219); font-family: Söhne, ui-sans-serif, system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, &quot;Helvetica Neue&quot;, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(68, 70, 84); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="border: 0px solid rgb(217, 217, 227); box-sizing: border-box; --tw-border-spacing-x:0; --tw-border-spacing-y:0; --tw-translate-x:0; --tw-translate-y:0; --tw-rotate:0; --tw-skew-x:0; --tw-skew-y:0; --tw-scale-x:1; --tw-scale-y:1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness:proximity; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; --tw-shadow:0 0 transparent; --tw-shadow-colored:0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; font-family: &quot;Söhne Mono&quot;, Monaco, &quot;Andale Mono&quot;, &quot;Ubuntu Mono&quot;, monospace !important; font-size: 0.875em; color: var(--tw-prose-code); font-weight: 600;">JSON_RPC_URL_&lt;chainID&gt;</code> = <strong style="border: 0px solid rgb(217, 217, 227); box-sizing: border-box; --tw-border-spacing-x:0; --tw-border-spacing-y:0; --tw-translate-x:0; --tw-translate-y:0; --tw-rotate:0; --tw-skew-x:0; --tw-skew-y:0; --tw-scale-x:1; --tw-scale-y:1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness:proximity; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; --tw-shadow:0 0 transparent; --tw-shadow-colored:0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; font-weight: 600; color: var(--tw-prose-bold);">insert your http endpoint here</strong>
<code style="border: 0px solid rgb(217, 217, 227); box-sizing: border-box; --tw-border-spacing-x:0; --tw-border-spacing-y:0; --tw-translate-x:0; --tw-translate-y:0; --tw-rotate:0; --tw-skew-x:0; --tw-skew-y:0; --tw-scale-x:1; --tw-scale-y:1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness:proximity; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; --tw-shadow:0 0 transparent; --tw-shadow-colored:0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; font-family: &quot;Söhne Mono&quot;, Monaco, &quot;Andale Mono&quot;, &quot;Ubuntu Mono&quot;, monospace !important; font-size: 0.875em; color: var(--tw-prose-code); font-weight: 600;">WEBSOCKET_URL_&lt;chainID&gt;</code> = <strong style="border: 0px solid rgb(217, 217, 227); box-sizing: border-box; --tw-border-spacing-x:0; --tw-border-spacing-y:0; --tw-translate-x:0; - [...]

2023-06-02 18:32 UTC, denverbaumgartner commented
@ishandhanani great work on this so far! just putting down my thoughts as a user here, will try to be clear in what i think is still needed before merging and what would be nice to have. 

before merge: 
- [ ] there is a pretty large `dif` between branch `allAboard` and `master` that are causing some merge conflicts. if you could merge `master` into `allAboard` and resolve those conflicts that would be 💯 happy to help out here if you get stuck on anything 
- [ ] when selecting tokens, we need a clear way to denote which is the asset and which is the quote of the pair 
- [ ] once merged with master - added premium input for the `riskminimized` and `targetvenueoutbid` strategies 

nice-to-have: 
- [ ] token selection: its not totally clear that the user needs to select two specific assets for a strategy, i think we should be explicit about this to make sure the user doesn't encounter any weird behavior. 
- [ ] market-aid selection: it would be great if we showed the user their existing market aid contracts and gave them the option to connect to one, instead of requiring them to manually provide the address
- [ ] market-aid selected: i think instead of option `7. Exit` we can say something like `7. Run the Bot`. we could even add an additional item like `8. Run the Bot` and give the user the option to exit if they so choose. just a little unclear what to do after you handle the aid-menu portion
- [ ] market-aid selected: being verbose here, i think we want to give the user an initial "health check" on their market aid once they connect to it. 1) have they approved the market aid for the assets they selected for the strategy, 2) what are the balances of the market aid for the strategy. we just want to make sure the user is prompted to set everything up properly before proceeding

again, let me know if you have any questions or if i can be of help here, great work so far!

2023-06-05 21:02 UTC, ishandhanani commented
Adding an update here just to track 

Before merge
1. Fixed those difs. All of Benjamins updates now play nice with the guidedStart flow that I created. Moral of the story is to always git pull 😭
2. Ive added some instructional prompts when the user is choosing their tokens. Before they confirm, it shows the user that they will be trading the pair X/Y. Let me know if I should add some additional prompts 
3. Work in progress

Nice to have
1.  Added logic to where the user has to choose 2 assets. Because the guidedStart flow is limited to the generic mm bot, I don't see the need to check multiples of two....but I can if needed
2. WIP
3. WIP
4. WIP

2023-06-07 19:59 UTC, denverbaumgartner commented
currently running into the following error when attempting to run `riskMinimized` strategy on `polygon-mumbai`: 
`Error: network does not support ENS (operation="getResolver", network="maticmum", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)`

having to hop from this review to handle something else atm, but will return and hopefully debug the issue on my side soon. i imagine this is probably an issue with my setup or rpc. 

some notes: 
- this health market aid health check is 🔥

some improvements for now: 
- [ ] i believe the premium can actually be greater than 1, in theory i do not believe there is a limit to the potential premium. i think here we should explain what the premium is. "Please provide a premium for your strategy (this is the additional spread, measured as a percent of price, to be applied to the strategy)" or something like that 

some improvements for later: 
- [ ] we should update the network selection map to prompt the user that the strategy selected will not work on that network if that is the case. for example, we are not currently deployed on arbitrum or polygon mainnet yet, and should notify the user accordingly. 
- [ ] if the user attempts to deposit >999 of an asset it results in `Error: invalid BigNumber string (argument="value", value="1e+21", code=INVALID_ARGUMENT, version=bignumber/5.7.0)`. we must be improperly handling these values under the hood and not depending upon `ethers` enough

2023-06-15 13:57 UTC, bghughes commented on configuration/config.ts
> +    strategy: any; //TODO: this should not be any there's def a type for it. Placeholder for now
Concerned that adding this will brick extant stuff, everything else seems fine

2023-06-15 20:47 UTC, bghughes commented on executionClients/marketMaking/index.ts
> -main();
This could be an issue, investigating

2023-06-15 20:48 UTC, bghughes commented on executionClients/marketMaking/index.ts
> -main();
This did indeed break the way I was starting bots straight from the command line with yarn so needs to be included IMO. Could you verify that the guided start is working as expected still? Assuming it is all still working we should be good to go @ishandhanani

2023-06-15 20:57 UTC, bghughes requested changes
Let's make sure all the command line starting flows still work correctly. I added back in the `main()` call (also check that doesn't cannibalize the `aid` stuff added) but am mainly concerned with the changes to `startGenericMarketMakingBotFromArgs` and `startGenericMarketMakingBot`. Just use different functions for the aid flow and this should all work together nicely

2023-06-15 20:57 UTC, bghughes commented on executionClients/marketMaking/index.ts
> -    if (userMarketAidAddress) {
I'm concerned with this, I worry it will fully brick `startGenericMarketMakingBot` from the command line. A quick fix would be: could you turn the pathing where they are doing the `aid` flow into a separate function entirely? Note the flow coming from `main()` that uses command line arguments, I want to make sure the `startGenericMarketMakingBot` flow that was already there doesn't break. My suspicion is that this code does indeed break that and instead overhauls this function when it should just use a new one 😄

2023-06-15 20:58 UTC, bghughes commented on executionClients/marketMaking/index.ts
> -    return startGenericMarketMakingBot(config, undefined,
This concerns me that it breaks the command line flows

2023-06-19 22:10 UTC, merged